[package]
name = "kpal"
version = "0.1.0"
authors = ["Kyle M. Douglass <kyle.m.douglass@gmail.com>"]
edition = "2018"

[workspace]

members = [
    "./",
    "kpal-peripheral",
]

[dependencies]
kpal-peripheral= { path = "kpal-peripheral" }
libloading = "0.5"
rouille = "3.0"
structopt = "0.2"