[package]
name = "kpal-peripheral"
version = "0.1.0"
authors = ["kmdouglass <kyle.m.douglass@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2"

[[example]]
name = "basic-peripheral"
crate-type = ["cdylib"]
