[package]
name = "kpal-peripheral"
version = "0.1.0"
authors = ["kmdouglass <kyle.m.douglass@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
env_logger = "0.6"
libc = "0.2"
log = "0.4"

[[example]]
name = "basic-peripheral"
crate-type = ["cdylib"]
