version: 2
jobs:
  build:
    docker:
      - image: rust:1

    steps:
      - checkout

      - run:
          name: Check formatting
          command: |
            rustup component add rustfmt
            cargo fmt -- --check

      - run:
          name: Build all targets
          command: cargo build --all --all-targets

      - run:
          name: Test all targets
          command: cargo test --all --all-targets
          environment:
            SERVER_ADDRESS: 0.0.0.0:8080
