[package]
name = "kpal-gpio-cdev"
version = "0.1.0"
authors = ["Kyle M. Douglass <kyle.m.douglass@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
env_logger = "0.6"
kpal-plugin = { path = "../kpal-plugin" }
gpio-cdev = "0.2"
libc = "0.2"
log = "0.4"
